apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mlops
  labels:
    app: mlops
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        app: mlops
    spec:
      containers:
      - image: minio
        name: minio
        ports:
        - containerPort: 8444
        resources: {}
      restartPolicy: Always
status: {}
