services:
  minio:
    container_name: minio
    image: minio/minio:latest
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9001:9001"
      - "9000:9000"
    entrypoint: sh
    command: '-c ''mkdir -p ./minio_data/mlflow && minio server /minio_data --console-address ":9001"'''
    networks:
      network:
        ipv4_address: 10.5.0.5

  mysql:
    image: mariadb:10.3
    container_name: mariadb
    hostname: mariadb
    env_file:
      - .env
    ports:
      - ${MYSQL_PORT1}:3306
      - ${MYSQL_PORT2}:33060
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/password1
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
    secrets:
      - password1
      - password2
    volumes:
      - database_volume:/var/lib/mysql
    networks:
      - network

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    hostname: phpmyadmin
    depends_on:
      - mysql
    env_file:
      - .env
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/password1
    secrets:
      - password1
    ports:
      - ${PHPMYADMIN_PORT}:80
    networks:
      - network

  mlflow:
    build:
      context: .
      dockerfile: Dockerfile.mlflow
    container_name: mlflow_tracker
    hostname: mlflow_tracker
    depends_on:
      - mysql
    env_file:
      - .env
#      - .secrets/env-secrets
    ports:
      - ${MLFLOW_PORT}:5000
    volumes:
      - /home/${USER_MLFLOW}/mlflow/mlruns:/home/${USER_MLFLOW}/mlflow/mlruns
    networks:
      - network

  custom_classifier:
    container_name: custom_classifier
    build:
      context: .
      dockerfile: Dockerfile.custom_classifier
    hostname: custom_classifier
    ports:
      - "5020"
    depends_on:
      - mysql
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    volumes:
      - /home/${USER_MLFLOW}/data/dataset:/custom_classifier/dataset
      - ../mlflow/mlruns:/home/${USER_MLFLOW}/mlflow/mlruns
    restart: always
    networks:
      - network

  nginx:
    container_name: nginx
    image: nginx:1.25.1
    volumes:
      - ../docker/configs/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ../docker/configs/nginx/certs:/etc/nginx/certs
    ports:
      - "80"
      - "443"
    depends_on:
      - mysql
      - phpmyadmin
      - mlflow
      - custom_classifier
    restart: always
    networks:
      - network

volumes:
  database_volume:

secrets:
  password1:
    file: ./mysql-root-password.txt
  password2:
    file: ./mysql-mlflowuser-password.txt

networks:
  network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
